モデルのバリデーションを追加
ryoken7090/highlight pull request #26
Opened 2021-07-07 05:40 UTC by dim0627

2021-07-10 05:06 UTC, ryoken7090 reviewed
その日のの反省と感謝したことに関しては空文字でも登録できるようにしたいと思っているので、presence: trueを削除しました

2021-07-10 05:11 UTC, dim0627 commented
それだとNullが防げなくない？

2021-07-10 05:16 UTC, ryoken7090 commented
modelで空文字だけはokにするバリデーションがさがせず、DBにnull: falseつけてればnull入らないのでいいのかなと思いました

2021-07-10 05:16 UTC, dim0627 commented
allow_blank, allow_nilっていうオプションがあるから覚えといてねって話したのに・・・

2021-07-10 05:16 UTC, ryoken7090 commented
そうでした...

2021-07-11 03:40 UTC, ryoken7090 commented
allow_blankやallow_nilを使ってnilだけ制限する方法がわからずexclusionヘルパーを利用しました
https://railsguides.jp/active_record_validations.html#exclusion

2021-07-11 06:00 UTC, dim0627 commented
いや、よく使うオプションなのでちゃんと使えるようになりましょう

2021-07-12 06:17 UTC, steiley requested changes

2021-07-12 06:17 UTC, steiley commented on app/models/diary.rb
> +  validates :energy, inclusion: { in: 1..10 }
```suggestion
  validates :concentration, presence: true, inclusion: { in: 1..10 }
  validates :energy, presence: true, inclusion: { in: 1..10 }
```

2021-07-13 05:40 UTC, merged