Diaryに新たにカラムを追加したためrspec直す
ryoken7090/highlight pull request #30
Opened 2021-07-09 08:17 UTC by ryoken7090

2021-07-12 22:48 UTC, dim0627 requested changes
https://github.com/willnet/rspec-style-guide
これ読んでないでしょ

2021-07-12 23:54 UTC, ryoken7090 commented on spec/factories/diaries.rb
> +    sequence(:reflection) { |i| "Reflection#{i}" }
ここ連番にする意味あるかわからない...

2021-07-12 23:55 UTC, ryoken7090 commented on spec/factories/diaries.rb
> +    date { Random.rand(Date.parse('2000/01/01') .. Date.parse('2100/12/31')) }
2100/12/31とかの唐突な感じ良くない気がする

2021-07-13 00:26 UTC, dim0627 commented on spec/factories/diaries.rb
> +    sequence(:reflection) { |i| "Reflection#{i}" }
意味なくてもやっといて損はないと思うよ

2021-07-13 00:27 UTC, dim0627 commented on spec/factories/diaries.rb
> +    date { Random.rand(Date.parse('2000/01/01') .. Date.parse('2100/12/31')) }
日付は無理にランダムにしなくていいかもね〜

2021-07-13 00:27 UTC, dim0627 commented on spec/requests/diaries_spec.rb
> +      let(:new_attributes) { FactoryBot.attributes_for(:diary) }
nice

2021-07-13 04:07 UTC, ryoken7090 commented on spec/factories/diaries.rb
> +    date { Random.rand(Date.parse('2000/01/01') .. Date.parse('2100/12/31')) }
気持ち悪いのでここは固定にしようとおもいます

2021-07-13 04:08 UTC, ryoken7090 commented on spec/factories/diaries.rb
> +    sequence(:reflection) { |i| "Reflection#{i}" }
わかりました！

2021-07-13 04:22 UTC, dim0627 approved these changes
:okke-:

2021-07-13 04:23 UTC, merged